title: "Médaille Militaire - Section pays de Saint Gilles Croix de Vie"
description: "Association des médaillés militaires - Section 1383"
baseurl: "/medaille-militaire"
url: "https://m3ph1s85.github.io"

# Cloudinary config
cloudinary_cloud_name: "votre-cloud-name"

# Blog settings
paginate: 6
paginate_path: "/actualites/page:num/"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed

# Association info (à personnaliser)
association:
  nom: "Médaille Militaire – Section pays de Saint Gilles Croix de Vie"
  fondee: "1976"
  president: "M. Christophe MATHIAS"
  contact: "MedMil1383@hotmail.com"
  adresse: "24 rue Athanase Boisliveau\n85220 l'Aiguillon-sur-Vie"
